// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmocvnpEGlP6bJVF104u-e3TxmUBwwj8E',
    appId: '1:357510000311:web:8755b34263f523314e2732',
    messagingSenderId: '357510000311',
    projectId: 'chat-app---flutter-f4800',
    authDomain: 'chat-app---flutter-f4800.firebaseapp.com',
    storageBucket: 'chat-app---flutter-f4800.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSONG3y_1WvMW_UIuvz41VE2lERI7v72M',
    appId: '1:357510000311:android:9625192d88110bd14e2732',
    messagingSenderId: '357510000311',
    projectId: 'chat-app---flutter-f4800',
    storageBucket: 'chat-app---flutter-f4800.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALC7dNwzvxWPYzxsKJ5xRY14meRo7kihI',
    appId: '1:357510000311:ios:d57ff85a5915aada4e2732',
    messagingSenderId: '357510000311',
    projectId: 'chat-app---flutter-f4800',
    storageBucket: 'chat-app---flutter-f4800.appspot.com',
    iosClientId: '357510000311-4k9mr43rpn9f3e1lh21jqkdohhkvd5d0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
